package clean

import "testing"

var both = Options{Trailers: true, Emdashes: true}

func TestMessage(t *testing.T) {
	tests := []struct {
		name string
		opts Options
		in   string
		want string
	}{
		{
			name: "clean message is untouched",
			opts: both,
			in:   "fix(api): reject empty payloads\n\nThe handler assumed a body.\n",
			want: "fix(api): reject empty payloads\n\nThe handler assumed a body.\n",
		},
		{
			name: "co-authored-by trailer and its blank separator",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
			want: "add parser\n",
		},
		{
			name: "generated-with footer with marker line",
			opts: both,
			in:   "add parser\n\nbody text\n\n\U0001F916 Generated with [Claude Code](https://claude.ai/code)\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
			want: "add parser\n\nbody text\n",
		},
		{
			name: "session trailer",
			opts: both,
			in:   "add parser\n\nClaude-Session: https://claude.ai/chat/abc\n",
			want: "add parser\n",
		},
		{
			name: "human co-author is kept",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Ada Lovelace <ada@example.com>\n",
			want: "add parser\n\nCo-Authored-By: Ada Lovelace <ada@example.com>\n",
		},
		{
			name: "co-author whose name is also an agent name is kept",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Devin Smith <devin@example.com>\n",
			want: "add parser\n\nCo-Authored-By: Devin Smith <devin@example.com>\n",
		},
		{
			name: "second co-author whose name is also an agent name is kept",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Jules Verne <jules@example.com>\n",
			want: "add parser\n\nCo-Authored-By: Jules Verne <jules@example.com>\n",
		},
		{
			name: "sign-off by a person surnamed Cursor is kept",
			opts: both,
			in:   "add parser\n\nSigned-off-by: Cursor Bell <cbell@example.com>\n",
			want: "add parser\n\nSigned-off-by: Cursor Bell <cbell@example.com>\n",
		},
		{
			name: "vendor name inside an unrelated host is kept",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Ada <ada@openai-research.example.com>\n",
			want: "add parser\n\nCo-Authored-By: Ada <ada@openai-research.example.com>\n",
		},
		{
			name: "ambiguous name with a product word is dropped",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Cursor Agent <cursoragent@cursor.com>\n",
			want: "add parser\n",
		},
		{
			name: "bot identity is dropped",
			opts: both,
			in:   "add parser\n\nCo-authored-by: google-labs-jules[bot] <jules@users.noreply.github.com>\n",
			want: "add parser\n",
		},
		{
			name: "vendor subdomain is dropped",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Devin <devin@mail.cognition.ai>\n",
			want: "add parser\n",
		},
		{
			name: "body prose mentioning an agent is kept",
			opts: both,
			in:   "add parser\n\nThe changelog is generated with Copilot from the commit log.\n\nmore body\n",
			want: "add parser\n\nThe changelog is generated with Copilot from the commit log.\n\nmore body\n",
		},
		{
			name: "signed-off-by naming an agent",
			opts: both,
			in:   "add parser\n\nSigned-off-by: Claude <claude@anthropic.com>\n",
			want: "add parser\n",
		},
		{
			name: "trailers kept when disabled",
			opts: Options{Emdashes: true},
			in:   "add parser\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
			want: "add parser\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
		},
		{
			name: "subject line is never dropped",
			opts: both,
			in:   "Generated by Claude: a note\n",
			want: "Generated by Claude: a note\n",
		},
		{
			name: "single spaced emdash becomes a colon",
			opts: both,
			in:   "refactor the parser — it was unreadable\n",
			want: "refactor the parser: it was unreadable\n",
		},
		{
			name: "spaced emdash after a colon becomes a comma",
			opts: both,
			in:   "fix(api): reject empties — the handler assumed a body\n",
			want: "fix(api): reject empties, the handler assumed a body\n",
		},
		{
			name: "paired emdashes become commas",
			opts: both,
			in:   "the parser — which is old — broke\n",
			want: "the parser, which is old, broke\n",
		},
		{
			name: "unspaced dash becomes a hyphen",
			opts: both,
			in:   "support the read—write split over 3–5 nodes\n",
			want: "support the read-write split over 3-5 nodes\n",
		},
		{
			name: "trailing dash is dropped",
			opts: both,
			in:   "drop the cache —\n",
			want: "drop the cache\n",
		},
		{
			name: "leading dash becomes a list hyphen",
			opts: both,
			in:   "changes\n\n— drop the cache\n",
			want: "changes\n\n- drop the cache\n",
		},
		{
			name: "colon later on the line still selects a comma",
			opts: both,
			in:   "drop the cache — the ttl was wrong: it counted twice\n",
			want: "drop the cache, the ttl was wrong: it counted twice\n",
		},
		{
			name: "dash inside a url is left alone",
			opts: both,
			in:   "see https://example.com/a—b — it explains the split\n",
			want: "see https://example.com/a—b: it explains the split\n",
		},
		{
			name: "url at the end of a line is not truncated",
			opts: both,
			in:   "see https://example.com/a—\n",
			want: "see https://example.com/a—\n",
		},
		{
			name: "line left empty by a dropped dash does not leave a gap",
			opts: both,
			in:   "subject\n\nbody\n\n—\n\nmore body\n",
			want: "subject\n\nbody\n\nmore body\n",
		},
		{
			name: "existing blank runs are preserved when nothing changes",
			opts: both,
			in:   "subject\n\n\nbody\n",
			want: "subject\n\n\nbody\n",
		},
		{
			name: "emdashes kept when disabled",
			opts: Options{Trailers: true},
			in:   "refactor the parser — it was unreadable\n",
			want: "refactor the parser — it was unreadable\n",
		},
		{
			name: "message without a trailing newline keeps its shape",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
			want: "add parser",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := Message(tt.opts, tt.in); got != tt.want {
				t.Errorf("Message() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestInspect(t *testing.T) {
	in := "fix the parser — it was unreadable\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n"
	got := Inspect(both, in)

	if len(got.RemovedLines) != 1 || got.RemovedLines[0] != "Co-Authored-By: Claude <noreply@anthropic.com>" {
		t.Errorf("RemovedLines = %q", got.RemovedLines)
	}
	if len(got.ChangedLines) != 1 {
		t.Fatalf("ChangedLines = %q", got.ChangedLines)
	}
	if got.ChangedLines[0].New != "fix the parser: it was unreadable" {
		t.Errorf("ChangedLines[0].New = %q", got.ChangedLines[0].New)
	}
}

func TestIdentity(t *testing.T) {
	tests := []struct {
		name    string
		address string
		want    bool
	}{
		{"Claude", "noreply@anthropic.com", true},
		{"Claude Opus 5", "noreply@anthropic.com", true},
		{"Cursor Agent", "cursoragent@cursor.com", true},
		{"google-labs-jules[bot]", "jules@users.noreply.github.com", true},
		{"Copilot", "copilot@github.com", true},
		{"andornaut", "andornaut@users.noreply.github.com", false},
		{"Devin Smith", "devin@example.com", false},
		{"Jules Verne", "jules@example.com", false},
		{"Ada", "ada@openai-research.example.com", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := Identity(tt.name, tt.address); got != tt.want {
				t.Errorf("Identity(%q, %q) = %v, want %v", tt.name, tt.address, got, tt.want)
			}
		})
	}
}

func TestInspectEmptyOnCleanMessage(t *testing.T) {
	if !Inspect(both, "fix(api): reject empty payloads\n").Empty() {
		t.Error("Inspect() reported findings for a clean message")
	}
}
