package clean

import "testing"

var both = Options{Trailers: true, Emdashes: true}

func TestApply(t *testing.T) {
	tests := []struct {
		name string
		opts Options
		in   string
		want string
	}{
		{
			name: "clean message is untouched",
			opts: both,
			in:   "fix(api): reject empty payloads\n\nThe handler assumed a body.\n",
			want: "fix(api): reject empty payloads\n\nThe handler assumed a body.\n",
		},
		{
			name: "co-authored-by trailer and its blank separator",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
			want: "add parser\n",
		},
		{
			name: "generated-with footer with marker line",
			opts: both,
			in:   "add parser\n\nbody text\n\n\U0001F916 Generated with [Claude Code](https://claude.ai/code)\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
			want: "add parser\n\nbody text\n",
		},
		{
			name: "session trailer",
			opts: both,
			in:   "add parser\n\nClaude-Session: https://claude.ai/chat/abc\n",
			want: "add parser\n",
		},
		{
			name: "human co-author is kept",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Ada Lovelace <ada@example.com>\n",
			want: "add parser\n\nCo-Authored-By: Ada Lovelace <ada@example.com>\n",
		},
		{
			name: "trailer key is matched without regard to case",
			opts: both,
			in:   "add parser\n\nco-authored-by: Claude <noreply@anthropic.com>\n",
			want: "add parser\n",
		},
		{
			name: "body prose mentioning an agent is kept",
			opts: both,
			in:   "add parser\n\nThe changelog is generated with Copilot from the commit log.\n\nmore body\n",
			want: "add parser\n\nThe changelog is generated with Copilot from the commit log.\n\nmore body\n",
		},
		{
			name: "signed-off-by naming an agent",
			opts: both,
			in:   "add parser\n\nSigned-off-by: Claude <claude@anthropic.com>\n",
			want: "add parser\n",
		},
		{
			name: "trailers kept when disabled",
			opts: Options{Emdashes: true},
			in:   "add parser\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
			want: "add parser\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n",
		},
		{
			name: "subject line is never dropped",
			opts: both,
			in:   "Generated by Claude: a note\n",
			want: "Generated by Claude: a note\n",
		},
		{
			name: "spaced emdash becomes a spaced hyphen",
			opts: both,
			in:   "refactor the parser — it was unreadable\n",
			want: "refactor the parser - it was unreadable\n",
		},
		{
			name: "unspaced dash becomes a hyphen",
			opts: both,
			in:   "support the read—write split over 3–5 nodes\n",
			want: "support the read-write split over 3-5 nodes\n",
		},
		{
			name: "a run of dashes becomes one hyphen",
			opts: both,
			in:   "drop the cache ——— it was wrong\n",
			want: "drop the cache - it was wrong\n",
		},
		{
			name: "dash inside a url is left alone",
			opts: both,
			in:   "see https://example.com/a—b — it explains the split\n",
			want: "see https://example.com/a—b - it explains the split\n",
		},
		{
			name: "url at the end of a line is not truncated",
			opts: both,
			in:   "see https://example.com/a—\n",
			want: "see https://example.com/a—\n",
		},
		{
			name: "a line holding one dash keeps its place in the body",
			opts: both,
			in:   "subject\n\nbody\n\n—\n\nmore body\n",
			want: "subject\n\nbody\n\n-\n\nmore body\n",
		},
		{
			name: "existing blank runs are preserved when nothing changes",
			opts: both,
			in:   "subject\n\n\nbody\n",
			want: "subject\n\n\nbody\n",
		},
		{
			name: "emdashes kept when disabled",
			opts: Options{Trailers: true},
			in:   "refactor the parser — it was unreadable\n",
			want: "refactor the parser — it was unreadable\n",
		},
		{
			name: "message without a trailing newline keeps its shape",
			opts: both,
			in:   "add parser\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
			want: "add parser",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got, _ := Apply(tt.opts, tt.in); got != tt.want {
				t.Errorf("Apply() = %q, want %q", got, tt.want)
			}
		})
	}
}

// The findings are what the scan tallies, so they have to name every line the
// rewritten message changed.
func TestApplyFindings(t *testing.T) {
	in := "fix the parser — it was unreadable\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n"
	_, got := Apply(both, in)

	if len(got.RemovedLines) != 1 || got.RemovedLines[0] != "Co-Authored-By: Claude <noreply@anthropic.com>" {
		t.Errorf("RemovedLines = %q", got.RemovedLines)
	}
	if len(got.ChangedLines) != 1 {
		t.Fatalf("ChangedLines = %q", got.ChangedLines)
	}
	if got.ChangedLines[0].New != "fix the parser - it was unreadable" {
		t.Errorf("ChangedLines[0].New = %q", got.ChangedLines[0].New)
	}

	if _, clean := Apply(both, "fix(api): reject empty payloads\n"); !clean.Empty() {
		t.Error("Empty() reported findings for a clean message")
	}
}

func TestIdentity(t *testing.T) {
	tests := []struct {
		name    string
		address string
		want    bool
	}{
		{"Claude", "noreply@anthropic.com", true},
		{"Claude Opus 5", "noreply@anthropic.com", true},
		{"Cursor Agent", "cursoragent@cursor.com", true},
		{"Devin", "devin@mail.cognition.ai", true},
		{"google-labs-jules[bot]", "jules@users.noreply.github.com", true},
		{"Copilot", "copilot@github.com", true},
		{"claude[bot]", "claude@users.noreply.github.com", true},
		{"gemini-code-assist[bot]", "gemini@users.noreply.github.com", true},
		{"andornaut", "andornaut@users.noreply.github.com", false},
		{"dependabot[bot]", "49699333+dependabot[bot]@users.noreply.github.com", false},
		{"renovate[bot]", "29139614+renovate[bot]@users.noreply.github.com", false},
		{"github-actions[bot]", "41898282+github-actions[bot]@users.noreply.github.com", false},
		{"pre-commit-ci[bot]", "66853113+pre-commit-ci[bot]@users.noreply.github.com", false},
		{"GitHub", "noreply@github.com", false},
		{"Devin Smith", "devin@example.com", false},
		{"Jules Verne", "jules@example.com", false},
		{"Cursor Bell", "cbell@example.com", false},
		{"Ada", "ada@openai-research.example.com", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := Identity(tt.name, tt.address); got != tt.want {
				t.Errorf("Identity(%q, %q) = %v, want %v", tt.name, tt.address, got, tt.want)
			}
		})
	}
}
